// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

[Table("Registration")]
public partial class Registration
{
    [Key]
    public int Id { get; set; }

    public string UserName { get; set; }
    [EmailAddress(ErrorMessage ="Not Valid Email")]
    public string Email { get; set; }

    [StringLength(16,ErrorMessage = "Should be Shorter Than 16"),MinLength(8,ErrorMessage ="Should be Longer Than 8")]
    public string Password { get; set; }

    [StringLength(16,ErrorMessage = "Should be Shorter Than 16"),MinLength(8, ErrorMessage = "Should be Longer Than 8")]
    [Compare("Password",ErrorMessage = "Passwords Not Matches")]
    public string PasswordCheck { get; set; }
}